# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './batch_geocoding_dialog.ui'
#
# Created: Fri Sep 14 17:20:58 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BatchGeocodingDialog(object):
    def setupUi(self, BatchGeocodingDialog):
        BatchGeocodingDialog.setObjectName(_fromUtf8("BatchGeocodingDialog"))
        BatchGeocodingDialog.resize(403, 360)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BatchGeocodingDialog.sizePolicy().hasHeightForWidth())
        BatchGeocodingDialog.setSizePolicy(sizePolicy)
        BatchGeocodingDialog.setWindowTitle(QtGui.QApplication.translate("BatchGeocodingDialog", "Batch geocoding", None, QtGui.QApplication.UnicodeUTF8))
        BatchGeocodingDialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(BatchGeocodingDialog)
        self.gridLayout.setContentsMargins(-1, -1, -1, 4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblRegion = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRegion.setFont(font)
        self.lblRegion.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Region:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegion.setObjectName(_fromUtf8("lblRegion"))
        self.gridLayout.addWidget(self.lblRegion, 2, 0, 1, 1)
        self.lblSettlement = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSettlement.setFont(font)
        self.lblSettlement.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "City:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSettlement.setObjectName(_fromUtf8("lblSettlement"))
        self.gridLayout.addWidget(self.lblSettlement, 4, 0, 1, 1)
        self.lblRayon = QtGui.QLabel(BatchGeocodingDialog)
        self.lblRayon.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "District:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRayon.setObjectName(_fromUtf8("lblRayon"))
        self.gridLayout.addWidget(self.lblRayon, 3, 0, 1, 1)
        self.line = QtGui.QFrame(BatchGeocodingDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.line_3 = QtGui.QFrame(BatchGeocodingDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 13, 0, 1, 4)
        self.line_2 = QtGui.QFrame(BatchGeocodingDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 11, 0, 1, 4)
        self.lblLayer = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLayer.setFont(font)
        self.lblLayer.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblLayer.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer.setObjectName(_fromUtf8("lblLayer"))
        self.gridLayout.addWidget(self.lblLayer, 0, 0, 1, 1)
        self.lblGeocoder = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGeocoder.setFont(font)
        self.lblGeocoder.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Geocoder:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGeocoder.setObjectName(_fromUtf8("lblGeocoder"))
        self.gridLayout.addWidget(self.lblGeocoder, 12, 0, 1, 1)
        self.bottomPanel = QtGui.QWidget(BatchGeocodingDialog)
        self.bottomPanel.setObjectName(_fromUtf8("bottomPanel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.bottomPanel)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.prgProcess = QtGui.QProgressBar(self.bottomPanel)
        self.prgProcess.setProperty("value", 0)
        self.prgProcess.setObjectName(_fromUtf8("prgProcess"))
        self.horizontalLayout.addWidget(self.prgProcess)
        self.btnRun = QtGui.QPushButton(self.bottomPanel)
        self.btnRun.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.horizontalLayout.addWidget(self.btnRun)
        self.gridLayout.addWidget(self.bottomPanel, 15, 0, 1, 4)
        self.lblAddress = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAddress.setFont(font)
        self.lblAddress.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddress.setTextFormat(QtCore.Qt.PlainText)
        self.lblAddress.setWordWrap(False)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout.addWidget(self.lblAddress, 5, 0, 1, 1)
        self.chkBuilding = QtGui.QCheckBox(BatchGeocodingDialog)
        self.chkBuilding.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Build. num:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBuilding.setObjectName(_fromUtf8("chkBuilding"))
        self.gridLayout.addWidget(self.chkBuilding, 6, 0, 1, 1)
        self.cmbLayer = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbLayer.setObjectName(_fromUtf8("cmbLayer"))
        self.gridLayout.addWidget(self.cmbLayer, 0, 1, 1, 3)
        self.cmbRegion = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbRegion.setObjectName(_fromUtf8("cmbRegion"))
        self.gridLayout.addWidget(self.cmbRegion, 2, 1, 1, 3)
        self.frmRayon = QtGui.QFrame(BatchGeocodingDialog)
        self.frmRayon.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmRayon.setFrameShadow(QtGui.QFrame.Raised)
        self.frmRayon.setObjectName(_fromUtf8("frmRayon"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frmRayon)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbRayonName = QtGui.QRadioButton(self.frmRayon)
        self.rbRayonName.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRayonName.setChecked(True)
        self.rbRayonName.setObjectName(_fromUtf8("rbRayonName"))
        self.gridLayout_2.addWidget(self.rbRayonName, 0, 0, 1, 1)
        self.rbRayonField = QtGui.QRadioButton(self.frmRayon)
        self.rbRayonField.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "From field", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRayonField.setChecked(False)
        self.rbRayonField.setObjectName(_fromUtf8("rbRayonField"))
        self.gridLayout_2.addWidget(self.rbRayonField, 2, 0, 1, 1)
        self.txtRayonName = QtGui.QLineEdit(self.frmRayon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRayonName.sizePolicy().hasHeightForWidth())
        self.txtRayonName.setSizePolicy(sizePolicy)
        self.txtRayonName.setObjectName(_fromUtf8("txtRayonName"))
        self.gridLayout_2.addWidget(self.txtRayonName, 0, 1, 1, 1)
        self.cmbRayonField = QtGui.QComboBox(self.frmRayon)
        self.cmbRayonField.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRayonField.sizePolicy().hasHeightForWidth())
        self.cmbRayonField.setSizePolicy(sizePolicy)
        self.cmbRayonField.setObjectName(_fromUtf8("cmbRayonField"))
        self.gridLayout_2.addWidget(self.cmbRayonField, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frmRayon, 3, 1, 1, 3)
        self.frmSettlement = QtGui.QFrame(BatchGeocodingDialog)
        self.frmSettlement.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmSettlement.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSettlement.setObjectName(_fromUtf8("frmSettlement"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frmSettlement)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rbSettlName = QtGui.QRadioButton(self.frmSettlement)
        self.rbSettlName.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSettlName.setChecked(True)
        self.rbSettlName.setObjectName(_fromUtf8("rbSettlName"))
        self.gridLayout_3.addWidget(self.rbSettlName, 0, 0, 1, 1)
        self.rbSettlField = QtGui.QRadioButton(self.frmSettlement)
        self.rbSettlField.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "From field", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSettlField.setObjectName(_fromUtf8("rbSettlField"))
        self.gridLayout_3.addWidget(self.rbSettlField, 2, 0, 1, 1)
        self.cmbSettlField = QtGui.QComboBox(self.frmSettlement)
        self.cmbSettlField.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSettlField.sizePolicy().hasHeightForWidth())
        self.cmbSettlField.setSizePolicy(sizePolicy)
        self.cmbSettlField.setObjectName(_fromUtf8("cmbSettlField"))
        self.gridLayout_3.addWidget(self.cmbSettlField, 2, 1, 1, 1)
        self.txtSettlName = QtGui.QLineEdit(self.frmSettlement)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSettlName.sizePolicy().hasHeightForWidth())
        self.txtSettlName.setSizePolicy(sizePolicy)
        self.txtSettlName.setObjectName(_fromUtf8("txtSettlName"))
        self.gridLayout_3.addWidget(self.txtSettlName, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frmSettlement, 4, 1, 1, 3)
        self.cmbAddress = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbAddress.setObjectName(_fromUtf8("cmbAddress"))
        self.gridLayout.addWidget(self.cmbAddress, 5, 1, 1, 3)
        self.cmbBuildingNum = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbBuildingNum.setEnabled(False)
        self.cmbBuildingNum.setObjectName(_fromUtf8("cmbBuildingNum"))
        self.gridLayout.addWidget(self.cmbBuildingNum, 6, 1, 1, 3)
        self.cmbGeocoder = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbGeocoder.setObjectName(_fromUtf8("cmbGeocoder"))
        self.gridLayout.addWidget(self.cmbGeocoder, 12, 1, 1, 3)

        self.retranslateUi(BatchGeocodingDialog)
        QtCore.QObject.connect(self.chkBuilding, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbBuildingNum.setEnabled)
        QtCore.QObject.connect(self.rbSettlField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSettlField.setEnabled)
        QtCore.QObject.connect(self.rbSettlName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtSettlName.setEnabled)
        QtCore.QObject.connect(self.rbRayonField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbRayonField.setEnabled)
        QtCore.QObject.connect(self.rbRayonName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtRayonName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(BatchGeocodingDialog)
        BatchGeocodingDialog.setTabOrder(self.cmbLayer, self.cmbRegion)
        BatchGeocodingDialog.setTabOrder(self.cmbRegion, self.txtRayonName)
        BatchGeocodingDialog.setTabOrder(self.txtRayonName, self.txtSettlName)
        BatchGeocodingDialog.setTabOrder(self.txtSettlName, self.cmbAddress)
        BatchGeocodingDialog.setTabOrder(self.cmbAddress, self.cmbGeocoder)
        BatchGeocodingDialog.setTabOrder(self.cmbGeocoder, self.btnRun)
        BatchGeocodingDialog.setTabOrder(self.btnRun, self.rbRayonName)
        BatchGeocodingDialog.setTabOrder(self.rbRayonName, self.rbRayonField)
        BatchGeocodingDialog.setTabOrder(self.rbRayonField, self.cmbRayonField)
        BatchGeocodingDialog.setTabOrder(self.cmbRayonField, self.rbSettlName)
        BatchGeocodingDialog.setTabOrder(self.rbSettlName, self.rbSettlField)
        BatchGeocodingDialog.setTabOrder(self.rbSettlField, self.cmbSettlField)
        BatchGeocodingDialog.setTabOrder(self.cmbSettlField, self.chkBuilding)
        BatchGeocodingDialog.setTabOrder(self.chkBuilding, self.cmbBuildingNum)

    def retranslateUi(self, BatchGeocodingDialog):
        pass

